import Footer from '../../components/Footer';
import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <nav className="shadow-md p-4 container mx-auto flex space-x-50 text-lg font-medium justify-between">
        <div>
          <h1 className='text-amber-600 text-4xl mx-15'>PEMPAK</h1>
        </div>
        
          <div className="container mx-auto flex space-x-5 text-lg font-medium ">
            <Link href="/" className="hover:text-blue-600 transition-colors my-2">Home</Link>
            <Link href="/about" className="hover:text-blue-600 transition-colors my-2">About</Link>
            <Link href="/contact" className="hover:text-blue-600 transition-colors my-2">Our Product</Link>
            <Link href="/services" className="hover:text-blue-600 transition-colors my-2">Services</Link>
            <Link href="/services" className="hover:text-blue-600 transition-colors my-2">Our Team</Link>
            <Link href="/services" className="hover:text-blue-600 transition-colors my-2">Blog</Link>
            <Link href="/services" className="hover:text-blue-600 transition-colors mx-12 text-white bg-amber-600 px-8 py-2 rounded-xl">Contact us</Link>
          </div>
        </nav>

        {/* Main Content */}
        <main>
          {children}
        </main>
         <Footer/>
      </body>
    </html>
  );
}
